# Generated by Django 3.1 on 2020-08-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User_Profile', 'verbose_name_plural': 'User_Profiles'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='personal_email',
            new_name='roche_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='external_id_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='external_id_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='maden_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_email_confirmed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pesel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_profile_status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_profile_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Not-Active'), (3, 'Prospect'), (4, 'Blocked')], default=1, verbose_name='USER_PROFILE_TYPE'),
        ),
    ]
