# Generated by Django 3.1 on 2020-08-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0005_parametersgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersgroup',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
