# Generated by Django 3.1 on 2020-08-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0007_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersgroup',
            name='country',
            field=models.CharField(choices=[('CH', 'CH - Swiss'), ('DE', 'DE - Germany'), ('IT', 'IT - Italia'), ('NL', 'NL - Netherlands'), ('PL', 'PL - Poland')], default=1, max_length=2, verbose_name='COUNTRY'),
        ),
    ]
