# Generated by Django 3.1 on 2020-08-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsm', '0008_auto_20200820_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersgroup',
            name='version',
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametersgroup',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
